>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|251 641249383 AM1_0257 TPR domain protein, putative [Acaryochloris marina MBIC11017]
MA----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------NVTLLDLN
KRSIELLNPKFELNKRNHKANYLRMSFQVSPDKYKQI-KSTELFNLYDEILVDTDLQFLD
----------------YSIDVYLELFLRPDL---VEEFSGLLSLSDPGSSGLRCLEQLSP
EHALLKTDSWLLTSIRQTQANREVYSKTIWAYLCVHEE--------------------QD
PLEQ--DLWSILSPFL------------QRVTESS-------------------------
------------LTNMLG-------QQNSFITTQ----------AY-QRWKSSVQN----
-----------MDEVKQENVQVLLKKLCE-----------EL-------GTISPEYHQQE
FSQSSVD------------QLSNGLDLPKGLNSGSSF----STSHPSNLGHLPIEEKRLS
QSTIWDLQR-QYYLQQGNTIFLQECEQQSSRQ-ARSKASHYAQLIF----SC--------
----LRDYCAINRRHKA-------------------------------------------
-----------------------------NYQAIDASQKIYLIELGAGSGHFAYQVLHHL
LPLLSQPTLKKISVC----------YVLTDFVTANIEFWKQHPSLQPFFKEGTLDIAYFD
IEYPTDLTLQISGDSLTPDTLNNPIILIANQVLSKLPQDAFCTESGKLSESRVRLFAPAG
HQLRDWRALGQIALQFSDV--GLDKSDYYEDAIANNILYTYSETNHPTHFL---------
FPTVALSCLDYFRHLSKDRLMIISSDFGYCHQNAWQGYGEPVFKLQGSVSLPVNYHVLAA
YTVQQGGLVLQPHRHTPDFYTQ-ALLFGKHPTQYQETQLCYQFYSTVTETDSWQGSV---
--------------QITTERMETLSLSQLIGYLHSHHWDSQIFLDCFSSLLDQLDTATPA
IRLDLIEGIHQIWTNYYPIGENQDLAFYLGMVLYQLAEYADAIDYFE-------------
-----------------------------------KSIQLTGTD----PATLYNISMCHF
HLQQLEETTT-----------------------------------YLQKALQADPSFEEA
LIFQRKLTQQQS------------------------HLDSGQTHH---------------
