>Arabidopsis_lyrata_gnl|BL_ORD_ID|18713 _470715|PACid:16052460
-----------------------------M------------------------------
-------------NPSLVTAINAP-------ISPSPRSPLLSHFLPSL-PHRF---SKSE
CL--TRRRYRVSFPRSSA---ASSDQL-S-------QAKNPGIHGDKKEL---------T
GLQ-----------------------------------------PIVEKMTPPVRLATSA
V---------VLAASLATGYGLGLRL-----AGSRNIAFGGAAVA--GAAGGAVVYALNS
AVPEVAAISL-------HNYVADF-----------ED-------------PASVTKDDVE
KIADRYGVNKGDEAFQAEICDI----YCRYVTSVLPTEGQ-------------SLKGDEV
AKIIKFKNALGID----EPDAAAMHMEIGRRIFRQRL------------ETGEREGDAEQ
RR---------------AFMRLVYVSAL--VFGDASS-------FLLPWKRVLKVTDAQV
EIAIRENAKQLYAERLK----------LVGRA--------INVENL--VD----------
----------------------LRKAQLSFKL----SDELAED-----LFRE-HTRKVVV
EN-------------------------ISSALSILKSR---T-------RAVKSLASVVE
ELEKVLEFNNLLVSLKSHSEADQFARGVGPISLIGDESD-------FERRMDDLKLLYR-
-----------------AYVTDA-LAGGRLEEN-----KLVAMSQLRNILGLGKREAEAI
SIDVTSKAYRKRLANAVSSGDLEAQDSKAKYLQKLCEELHFDAQKAGAIHEEIYRQKLQQ
CV-T---DGELSDDNVAALLRLRVMLCIPQQTVETAHAEICG------TIFEKVVRDAIS
SGVDG-------YDAETRKSVRKAAHGL--------------------------------
--------------------------RLSRETAMSI--ASKAV-RRVFTNYIRRAR--AA
EN----------------------------------------------------------
-----------------RTESAKELKK----------MIAFNTL--VVTEMVADIKGESS
--------------------DK-APEEDPV----------------EEKE-EDGE-D---
----------------EEWGSLESLRKT-R---PNKELAEKM----G-KPGQTEITLK--
--------------DDLPDR--------DRIDLY--------KTYLLYCVTGEVTRIPFG
AQIT------TKR--DDSEYLLLNQLGGILGLSSKEIVNIHVGLAEQAFRQQAEVILADG
QLTKARVEQLDELQ---KQVGLPQ-PQAEKVIKNITTTKMANAIETAVN-----------
---------------------------------------------QGRLNIKQIRELKEA
NVSLDS------MIAVSLREKLFKKTV------------NDIFSSGTGEFDEIEVYQTIP
SDLSIDVEKAKRVVHDLAQSRLSNSLVQAVALLRQRNSKGVVSSLNDLLA-CDKAVPAE-
PMSWEVSEELSDLYAIYSK---------SDPKPAPEKVSRLQYLLGIDDSTATALR----
-EM-EDGALSSAA---E-EGNFV-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------F
>gnl|BL_ORD_ID|12589 Arabidopsis_thaliana AT1G06950.1|PACid:19650536
-----------------------------M------------------------------
-------------NPSLVTAINAP-------ISPSPRSPLLSHFLPTL-PHRF---SKSE
CL--SRRRYRVSFPRSSA---ASSDQL-SVS----TQAKNPGIHGNKKEL---------T
GLQ-----------------------------------------PIVEKMTPPVRLATSA
V---------VLAASLATGYGLGLRL-----AGSRNIAFGGAAVA--GAAGGAVVYALNS
AVPEVAAISL-------HNYVAEF-----------ED-------------PASVTKDDVE
KIADRYGVNKGDEAFQAEICDI----YCRYVTSVLPTEGQ-------------SLKGDEV
AKIVKFKNALGID----EPDAAAMHMEIGRRIFRQRL------------ETGEREGDAEQ
RR---------------AFMRLVYVSAL--VFGDASS-------FLLPWKRVLKVTDAQV
EIAIRENAKQLYAERLK----------LVGRD--------INVENL--VD----------
----------------------LRKSQLSFKL----SDELAED-----LFRE-HTRKVVV
EN-------------------------ISSALSILKSR---T-------RAAKSLASVVE
ELEKVLEFNNLLVSLKSHSEADQFARGVGPISLIGDESD-------FERRMDDLKLLYR-
-----------------AYVTDA-LSGGRLEEN-----KLVAMSQLRNILGLGKREAEAI
SVDVTSKSYRKRLANAVSSGDLEAQDSKAKYLQKLCEELHFDAQKAGAIHEEIYRQKLQQ
CV-T---DGELSDDNVAALLRLRVMLCIPQQTVDTAHAEICG------TIFEKVVRDAIS
SGVDG-------YDAETRKSVRKAAHGL--------------------------------
--------------------------RLSRETAMSI--ASKAV-RRVFTNYIRRAR--AA
EN----------------------------------------------------------
-----------------RTDSAKELKK----------MIAFNTL--VVTEMVADIKGESS
--------------------DK-APEEDPV----------------QEKE-EDDE-D---
----------------EEWGSLESLRKT-R---PDKELAEKM----G-KPGQTEITLK--
--------------DDLPDR--------DRIDLY--------KTYLLYCVTGEVTRIPFG
AQIT------TKR--DDSEYLLLNQLGGILGLSSKEIVNIHVGLAEQAFRQQAEVILADG
QLTKARVEQLDELQ---KQVGLPQ-PQAEKVIKNITTTKMANAIETAVN-----------
---------------------------------------------QGRLNIKQIRELKEA
NVSLDS------MIAVSLREKLFKKTV------------SDIFSSGTGEFDETEVYQTIP
SDLSIDVEKAKRVVHDLAQSRLSNSLVQAVALLRQRNSKGVVLSLNDLLA-CDKAVPAE-
PMSWEVSEELSDLYAIYSK---------SDPKPAPEKVLRLQYLLGIDDSTATALR----
-EM-EDGALSSAA---E-EGNFV-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------F
>Thellungiella_halophila_gnl|BL_ORD_ID|5952 _Thhalv10006671m|PACid:20185466
-----------------------------M------------------------------
-------------NPSLITSINAP-------ISPSTRSPLLCHFLTPL-PLRF---S---
----KNRRYRVSFPRCAA---TSSDLP-LVS----EQAKKPDVYGNKKEL---------T
GLQ-----------------------------------------SIVEKMTPPVRLATSA
V---------VLAASLAAGYGLGLRF-----SGSRNIALGGAAVA--GAAGGGLVYALNS
AVPEVAATSL-------HNFVAEF-----------ED-------------PASVTKEDIE
RIADRYGVNKGDEAFLAEICDI----YCRYVTSVLPTEGQ-------------SLKGDEV
EKIVKFKNALGID----DPDAASMHMEIGRRIFRQRL------------ETGEREGDAEQ
RR---------------AFMRLVYVSAL--VFGDAAS-------FLLPWKRVLKVTDAQV
EIAIRENAKQLYAERLK----------SVGRD--------INVENL--VD----------
----------------------LRKAQLSFKL----SDELAED-----LFRE-HTRAVAV
EN-------------------------ISSALGVLKSR---T-------RAVKSMALVVE
ELEKVLDFNNLLVSLKSHSEADQFARGVGPISLIGGESD-------FERRMDDLKLLYR-
-----------------AYVTDA-LSGGRIEEN-----KLVAMSQLRNILGLGTREAEAI
SVDVTSKAYRKRLSSAVSTGDLEAQDSKAKYLQKLCEELHFDAQKASAIHEEIYRQKLQQ
CV-A---GGELSEVSVASLLRLRVMLCIPQQTIEAAHAEICG------SIFEKVVRDAIS
SGVDG-------YDAETRKSVRKAAHGL--------------------------------
--------------------------RLSRETAMSI--ASKAV-RRVFTNYIRRAR--AA
EN----------------------------------------------------------
-----------------RTESAKELKK----------MIAFNTL--VVTEMVADIKGESS
--------------------DK-ASEE-PV----------------QEKE-EAGE-D---
----------------EEWGSLESLRKT-R---PDKELAEKM----G-KPGQTEITLK--
--------------DDLPDR--------DRIDLY--------KTYLLYCLTGEVTRIPFG
AQIT------TKR--DDSEYLLLNQLGGILGLTSKEIVNIHVGLAEQAFRQQAEVILADG
QLTKARVEQLDELQ---KQVGLPQ-PQAEKVIKNITTTKMANAIETAVN-----------
---------------------------------------------QGRLNIKQIRELKEA
NVSLDS------MIAVSLREKLFKKTV------------NDIFSSGTGEFDETEVYETIP
ADLSIDVEKAKGVVHDLARSRLSNSLIQSVALLRQRNAKGVVSSLNDLLA-CDKAVPAE-
PMSWEVSEELSDLYDIYSK---------SDPKPAPEKVSRLQYLLGIDDSTATALR----
-EM-EDGALSSSA---E-EGNFV-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------F
>QUERY_Arabidopsis_lyrata_gnl|BL_ORD_ID|13077 _887909|PACid:16046824
-----------------------------M------------------------------
------------------------------------------------------------
------------------ERPPTSEVARAPIAVYWDMKMCPVPYGYDARRVG-------P
FIE-----------------------------------------SNLRQLGYTGPITITA
VGLLSDVPEQILEALFSSGVSLSNVP--------YGTRDVATLVLFRTFDFPPPASFMVI
SHPEDAAVFLDLVSEIGYNTIFPFPLKEAASHLEDDDGKPLWENFLRAEPPEE-------
--------DKCSETGQSWVCRVCHGVTGRDFQSFMTHLSTPKHIWEFPRWHTYATSGNQI
PCVSSDESVDAVEEAPLDSYPENATIMIGRRIFRQRL------------ETGEREGDAEQ
RRKESISVITSCMLPVQAFMRLVYVSAL--VFGDASS-------FLLPWKRVLKVTDAQ-
------------------------------------------------------------
---------------------------------------LAED-----LFRE-HTRKVVV
EN-------------------------ISSALSILKSR---T---------LAALASVVE
ELEKVLEFNNLLVSLKSHSEADQFACG------VGDESD-------FERRMDDLKLLYR-
-----------------AYVTDA-LSGGRIAEN-----KLVAMSQLRNILGLGKREAEAI
SVDVTSKAYRKRLANAVSNGDLEAQDSKAKYLQKLCEELHFDAQMAGAIHEEIYRQKLQQ
CVI----DGELSDDNVAALLRLRVMLCIPQQTVETAHAEICG------TIFEKVVREAIS
SGVDG-------YDAETRKSVRKAAHGL--------------------------------
--------------------------RLSRETAMCI--ASKAV-RMVFTNYIRRAR--AA
EN----------------------------------------------------------
-----------------RTESAKELKK----------MIAFNTL--VVTEMVTDIKGESS
--------------------DK-APEEDPA------------------EMVAKEK-----
-------------TVSGNLQRSQILRSKVL--------GKQRIKNPN-YKGKWKNPWI--
--------------DNPEFE--------DDPDLY--------VLKPIKYAGIEVWQVKAG
SIFD------NILICDDPEYA--------------------RSIVDDYFAQHRES--EKE
LFAEAEKEKLEKMS---YEHGHTN-RCLQEARKA--------------------------
---------------------------------------------REEGERRRKERDHRY
G---------------DRRRRYKRPNP------------RDYMDDYHDEL----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------
>gnl|BL_ORD_ID|16787 Arabidopsis_thaliana AT1G08450.2|PACid:19654734
-----------------------------M-G----------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------LPQNKL-SFFCFFFLV
SVLT--L----APLA---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------FSEIFLEEHF------------E----GG-WKS
RW------------------------------------------VLSDWKRNEGKAGTFK
HTAGKWPGD-------------------------------PD-NKG--IQ----------
----------------------TYNDAKHYAI----SAKI-PE------FSN--------
-----------------------------------KNR---T-------LVVQYSVKIEQ
DIE------------------------------CGGAY---------------IKLL---
--------------------------SGYVNQK-----QFGGDTP---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------YSVLVD--NKER--EF
GS------------------------------------------MYTDWD--ILPP----
-----------------RKIKVKNAKK----------PEDWDDR--EYIDDPNDVKPEGF
--------------------DS-IPREIPD------------------RKAKEPE-DWDE
-------------EENGLWEPPKIPNSAYK-----GPWKAKRIKNPN-YKGKWKNPWI--
--------------DNPEFE--------DDPDLY--------VLKSIKYAGIEVWQVKAG
SIFD------NILICDDPAYA--------------------RSIVDDYFAQHRES--EKE
LFAEAEKERKARED---EE---AR-IARE-------------------------------
---------------------------------------------EGE--RRRKERDHR-
YG--DR------------RRRYKRPN-------------P-----------RDYM-D---
------------------------------------------------------------
-----------DY------------------------------------H----------
---------------DE-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------L
>Thellungiella_halophila_gnl|BL_ORD_ID|6837 _Thhalv10007710m|PACid:20186356
-----------------------------M-G----------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------FPQNKFNSCFSFFFLF
SFLT--L----APLA---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------FSEIFLEERF------------E----GG-WKS
RW------------------------------------------VLSDWKRNEGKAGTFK
HTAGKWPGD-------------------------------PD-DKG--IQ----------
----------------------TYNDAKHYAI----SAKI-PE------FSN--------
-----------------------------------KNR---T-------LVVQYSVKIEQ
DIE------------------------------CGGAY---------------IKLL---
--------------------------SGYVNQK-----QFGGDTPYSLMFG---------
------------------------------------------------------------
-------------------------------------PDICG------TQTKKL---HVI
LSYQG-------QNYPIKKDLQCETD----------------------------------
--------------------------KLTHFYTFIL--RPDAS-YSVLVD--NKER--EF
GS------------------------------------------MYTDWD--ILPP----
-----------------RKIKVKNAKK----------PEDWDDR--EYIDDPNDVKPEGF
--------------------DS-IPRQIPD------------------PKAKEPE-DWDE
-------------EENGLWQPPKIPNPAFK-----GPWKAKKIKNPN-YKGKWKNPWI--
--------------DNPEFE--------DDPDLY--------VLKPIRYVGIEVWQVKAG
SIFD------NILISDDPQHA--------------------RSIVDDYFDQHRES--EKE
LFAEAEKERKARED---EE---SR-KARE-------------------------------
---------------------------------------------EGE--RRRKERDHR-
YG--DR------------RRRYKRPN-------------P-----------RDYM-D---
------------------------------------------------------------
-----------DY------------------------------------H----------
---------------DE-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------L
>Thellungiella_halophila_gnl|BL_ORD_ID|21568 _Thhalv10023481m|PACid:20201192
-----------------------------M------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------AKLNPNIVSL
ILIG--L----VSIA---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------SAEVIFEERF------------D----DG-WEN
RW------------------------------------------VKSDWKKDENTAGEWN
HTSGNWSGD-------------------------------AN-DKG--IQ----------
----------------------TSEDYRFYAI----SAEF-PE------FSN--------
-----------------------------------KDK---T-------LVFQFSVKHEQ
KLD------------------------------CGGGY---------------MKLL---
--------------------------SGDVDQK-----KFGGDTPYSIMFG---------
------------------------------------------------------------
-------------------------------------PDICG------YSTKKV---HAI
LTYNG-------TNHLIKKEVPCETD----------------------------------
--------------------------QLTHVYTFVL--RPDAT-YSILID--NVEK--QT
GS------------------------------------------LYSDWD--LLPA----
-----------------KKIKDPSAKK----------PEDWDDK--EYIPDPEDKKPAGY
--------------------DD-IPKEIPD------------------ADAKKPE-AWDD
-------------EEDGEWTAPTIPNPEYN-----GEWKPKKIKNPN-YKGKWKAPMI--
--------------DNPDFK--------DDPELY--------VFPKLKYVGVELWQVKSG
SLFD------NVLVCDDPEYA--------------------KKLAEETWGKHKDA--EKA
AFDEAEKKREEEES---KD---APAADSD-------------------------------
---------------------------------------------AED----GAEDDDH-
EG--DE------SDTESKSEETKEASD------------N-----------DEDD-----
------------------------------------------------------------
-----------AA------------------------------------H----------
---------------DE-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------L
