>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|251  641249383 AM1_0257 TPR domain protein, putative [Acaryochloris marina MBIC11017]

M-------------------------ANVTLLDLNKRSIELLNPKFELNKRNHKANYLRM
SFQVSPDKYKQIKSTELFNLYDEILVDTDLQFLDYSIDVYLELFLRPDLVEEFSGLLSLS
DPGSSGLRCLEQLSPEHALLKTDSWLLTSIRQTQANREVYSKTIWAYLCVHEEQDPLEQD
LWSILSPFLQRVTESSLTNMLGQQNSFITTQAYQRWKSSVQNMDEVKQENVQVLLKKLCE
ELGTISPEYHQQEFSQSSVDQLSNGLDLPKGLNSGSSFSTSHPSNLG-------------
------HLPIEEKRLSQSTIWDLQRQYYLQQGNTIFLQECEQQSSRQARSKASHYAQLIF
SCLRDYCAINRRHKANYQAIDASQKIYLIELGAGSGHFAYQVLHHLLPLLSQPTLKKISV
CYVLTDFVTANIEFWKQHPSLQPF------------------------------------
------------------------------------------------------------
--------------FKEGTLDIAYFDIEYPTDLTLQISGDSLTPDTLNNPIILIANQVLS
KL--PQDAFCTESGKLSESRVRLFAPAGHQLRDWRALGQIALQFSDVGLDKSDYYEDAIA
NNILYTYSETNHPTHFLFPTVALSCLDYFRHLSKDRLMIISS------------------
----------------DFGYC-------------------------------------HQ
NAWQGYGEPVFKLQGS-----------------------------------VSLPVNYHV
LAAYTVQQGGLVLQPHRHTPDFYTQALLFGKHPTQYQETQL----CYQFY---STVT---
---------------------ETDSWQGSVQITTERMETLSLSQLIGYLHSHHWDSQIFL
DCFSSLLDQLDTATPAIRLDLIEGIHQIW----------TNYYPIGENQDLAFYL-----
------GMVLYQLAEYADAIDYFEKSIQLTGTDPATLYNISMCHFHLQQLEETTTYLQKA
LQADP----SFEEALIFQRKLTQQQSHLDSGQTHH-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------
>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|251 641249383 AM1_0257 TPR domain protein, putative [Acaryochloris marina MBIC11017]
MANVTLLDLNKRSIELLNPKFELNKRNHKANYLRMSFQVSPDKYKQIKSTELFNLYDEIL
VDTDLQFLDYSIDVYLELFLRPDLVEEFSGLLSLSDPGSSGLRCLEQLSPEHALLKTDSW
LLTSIRQTQANREVYSKTIWAYLCVHEEQDPLEQDLW--SILSPFLQRVTESSLTNMLGQ
QNSFITTQAYQRWKSSVQNMDEVKQENVQVLLKKLCEELGTISPEYHQQEFSQSSVDQLS
NGLDLPKGLN------SGSSFSTSHPSNLGHLPIEEKRLSQSTIWDLQRQYYLQQGNTIF
LQECEQQSSRQARSKASHYAQLIFSCLRDYCAINRRHKANYQAIDASQKIYLIELGA---
---------------------------------------------GSGHFAYQVLHHLLP
LLSQPTLKKISVCYVLTDFVTANIEFWKQHPSLQPFFKEGTLDIAYFDIEYPTDLTLQIS
GDSLTPDTLNNPIILIANQVLSKLPQDAFCTESGKLSESRVRLFAPAGHQLRDWRALGQI
ALQFSDVGLDKSDYYE-----------------DAIANNILYTYSETNHPTHFLFPTVAL
SCLDYFRHLSKDRLMIISSDFGYCHQNAWQGYG----------EPVFKLQGSVSLP----
-------------------------VNYHVLAAYTVQQGGLVLQPHRHTPDFYTQALLFG
K---------------------HPTQYQETQLCYQFYSTVTETDSWQGSVQITTERMET-
-------LSLSQLIGYLHSHHWDSQI----------------FLDCFSSLL-----DQLD
TATPAIRLDLIEGIHQIWTNYYPIGENQDLAFYLGMVLYQLA--------EYADAIDYFE
KSIQLTGTDPATLYNISMCHF--------HLQQLEETTTYLQKALQ-ADPS---------
-------------------------------------FEEALIFQRKLTQQQSH------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------LDSGQTHH
>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|251 641249383 AM1_0257 TPR domain protein, putative [Acaryochloris marina MBIC11017]
MANVTLLDLNKRSIELLNPKFELNKRNHKANYLRMSFQVSPDKYKQIKSTELFNLYDEIL
VDTDLQFLDYSIDVYLELFLRPDLVEEFSGLLSLSDPGSSG-LRCLEQLSPEHALLKTDS
WLLTSIRQTQANREVYSKTIWAYLCVHEEQDPLEQDLWSILSPFLQRVTES--SLTNMLG
QQNSFITTQAYQRWKSSVQNMDEVKQENVQVLLKKLCEELGTISPEYHQQEFSQSSVDQ-
--LSNGLDLPKGLNSGSSFSTSHPSNLGHLPIEEKRLSQSTIWDLQRQYYLQQGNTIFLQ
ECEQQSSRQARSKASHYAQLIFSCLRDYCAINRRHKANYQAIDASQKIYLIELGAGSGHF
AYQVLHHLLPLLSQPTLKKISVCYVLTDFVTANIEFWKQHPSLQPFFKEGTLDIAYFDIE
YPTDLTLQISGDSLTPDTLNNPIILIANQVLSKLPQDAFCTES--GKLSESRVRLF-APA
GHQLRDWRALGQIALQFSDVGLDKSDYYEDAIANNILYTYSETNHPTHFLFPTVALSCLD
YFRHLSKDRLMIISSDFGYCHQNAWQGYGEPVFKLQGSVSLPVNYHVLA----AYTVQQG
GLVLQPHRHTP-DFYTQALLFGKHPTQYQETQL---------------------------
--CYQFYSTVTETDSWQGSVQITTERMETLSLSQLIGYLHSHHWDSQIFLDCFSSLLDQL
DTATPAIRLDLIEGIHQIWTNYYPIGENQDLAFYLGMVLYQLAEYADAIDYFEKSIQLTG
TDPATLY---NISMCHFHLQQLEETTTYLQKALQADPS----------------------
-FEEALIFQRKLTQQ---------------------------------------------
------------------------------------------------------------
---------------QSHLDSGQT------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------HH
>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|251 641249383 AM1_0257 TPR domain protein, putative [Acaryochloris marina MBIC11017]
MANVTLLDLNKR-------------SIELLNP------------KFELNKRNHKANYL--
-----------------RMSFQVSPDKYKQIKSTE-------------LFNLYDE-----
-----ILVDTDLQFLDYSIDVYLELFLRPDLVE---------------------------
------------------------------------------------------------
------------------------------------------EFSGLLSLSDPGSSGLRC
LEQLSPEHALLKTDSWLLTSIRQTQANREVYSKTIWAYLCVHEEQDPLEQDLWSILSPFL
QRVTES-SLTNMLG--QQNSFITTQAYQRWKSSVQNMDEVK----QENVQVLLK-----K
LCEELGTISP--------------EYHQQEFSQSSVDQLSNGLD-----LPKGLNSGSSF
STSHPSNLGHLPIEEKRLSQSTIWDLQRQYYLQQ------GN--------TIFLQECEQQ
SSRQARSKASHYAQLIFSCLRDYCAINRRHKANYQAIDASQKIYLIELGAGSGHFAYQVL
HHLLPLLSQ-----------PTLKKISVCYVLTDFVTANIEFWKQHPSLQ----------
PFFKEGTLDIA--------------YFDIEYPTDLTLQISGDSLTPDTLNN---------
--PIILIANQVLSKL-PQDAFCTESGKLSESRVRLFAPAGHQLRDWRALGQIALQFSDVG
LDKSDYYEDAIANNILYTYSETN----------------HPTHFLFPTVALSCLDYFRHL
SKDRLMIISSDFGYCHQNAWQGYGEPVFKLQGSVSLPVNYHVLAAYTVQQGGLVLQPHRH
TPDFYTQALLFGKHPTQYQETQLCYQFYSTVTETDSWQGSVQITTERMETLSLSQLIGYL
HSHHWDSQIFLDCFSSLLDQLDTATPAIRLDLIEGIHQIWTNYYPIGENQDLAFYLGMVL
YQLAEYADAIDYFEKSIQLTGTDPATLYNISMCHFHLQQLEETTTYLQKALQADPSFEEA
LIFQRKLTQ---------------------------------------------------
----------------QQSHLDSGQT----------------------------------
---HH
>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|251 641249383 AM1_0257 TPR domain protein, putative [Acaryochloris marina MBIC11017]
MA-------NVTLLDLNKRSIELLNPKFELNKRNHKANYLRMSF---------------Q
VSPDKYKQIKSTELFNLYDEILVDTDLQFLDYSIDVYLELFLRPDLVEEFSGLLSLSDPG
SSGLRCLEQLSPEHALLK---TDSWLLTSIRQTQANREVYSKTIWAYLCVHEEQDPLEQD
LWSILSPFLQRVTESSLTNMLGQQNSFITTQAYQRWKSSVQNMDEVKQENVQVLLKKLCE
ELGTISPEYHQQEFSQSSVDQLSNGLDLPKGLNSGSSFSTSHPSNLGHLPIEEKRLSQST
IWDLQRQYYLQQGNTIFLQECEQQSSRQARSKAS--------------------------
--HYAQLIFSCLRDYCAINRRHKANYQAIDASQKIYLIELGAGSGHFAYQVLHHLLPLLS
QPTLKKISVCYVLTDFVTANIEFWKQHPSLQPFFKEGTLDIAYFDIEYPTDLTLQISGDS
LTPDTLNNPIILIANQVLSKLPQDAFCTESGKLSESRVRLFAPAGHQLRD----WRALGQ
IALQFSDVGLDKSDYYEDAIANNILYTYSETNHPTHFLFPTVALSCLDYFRHLSKDRLMI
ISSDFGYCHQNAWQGYGEPVFKLQGSVSLPVNYHVLAAYTVQQGGLVLQPHRHTPDFYTQ
ALLFGKHPTQYQETQLCYQFYSTVTET----------------------DSWQGSVQITT
ERMETLSLSQLIGYLHSHHWDSQIFLDCFSSLLDQLDTATPAIRLDLIEGIHQIWTNYYP
IGENQDLAFYLGMVLYQLAEYADAIDYFEKSIQLTGTDPATLYNISMCHFHLQQLEETTT
YLQKALQADPSFEEALIFQRKLTQQQSHLDSGQTHH------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------
>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|251 641249383 AM1_0257 TPR domain protein, putative [Acaryochloris marina MBIC11017]
M------------ANVTLLDLNKRSIELLNPKFELNKRNHKANYLRMSFQVSPDKYKQIK
STELFNLYDEILVDTDLQFLDYSIDVYLELFLRPDLVEEFSGLLSLSDPGSSGLRCLEQL
SPEHALLK--TDSWLLTSIRQTQANREVYSKTIWAYLCVHEEQDPLEQDLWSILSPFLQR
VTESSLTNMLGQQNSFITTQAYQRWKSSVQNMDEVKQENVQVLLKKLCEELGTISPEYHQ
QEFSQSSVDQLSNGLDLP-----KGLNSGSSFSTSHPSNLGHLPIEEKRLSQST------
---------IWDLQRQYYLQQGNTIFLQECEQQSSRQARSKASHYAQLIFSCLRDYCAIN
RRHKANYQAIDASQKIYLIELGAGSGHFAYQVLHHLLPLLSQPTLKKISVCYVLTD----
-FVTANIEFWKQHPSLQPFFKEGTLDIAYFDIEYPTDLTLQISGDSLTPDTLNNPIILIA
NQVLS------------------------KLPQDAFCTESGKLSE---------------
--------SRVRLFAPAGHQLRDWRALGQIALQFSDVGLD------KSDYYEDAIANNIL
YTYSETNHPTHFLFPTVALSCLDYFRHLSKDRLMIISSDFGYCHQNAWQGYGEPVFKLQG
SVSLPVNYHVLAAYTVQQGGLVLQPHRHTPDFYTQALLFGK-----HPTQYQETQLCYQF
YSTVTETDSW----QGSVQITTERMETLSLSQLIGYLHSHHWDSQIFLDCFSSLLDQLDT
ATPAIRLDLIEGIHQIWTNYYPIGENQDLAFYLGMVLY-QLAEYADAIDYFEKSIQLTGT
DPATLYNISMCHFHLQQLEETTTYLQKALQADPSFEEALIF-------------------
---------------------------QRKLTQQQSHLDSGQT-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----HH
>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|251 641249383 AM1_0257 TPR domain protein, putative [Acaryochloris marina MBIC11017]
MANVTLLDLNKRSIELLNPKFELNKRNHKANYLRMSFQVSPDKYKQIKSTELFNLYDEIL
VDTDLQFLDYSIDVYLELFLRPDLVEEFSGLLSLSDPGSSGLRCLEQLSPEHALLKTDSW
LLTSIRQTQANREVYSKTIWAYLCVHEEQDPLEQD------------LWSILSPFLQRVT
ESSLTNMLGQQNSFITTQAYQR--------------------WKSSVQNMDEVKQENVQV
LLKKLCEELGTISPEYHQQEFSQSSVDQLSNGLDLPKGLNSGSSFSTSHPS-NLGHLPIE
EKRLSQSTIWDLQRQYYLQQGNTIFLQECEQQSSRQARSKASHYAQLIFSCLRDYCAINR
RHKANYQAIDASQKIYLIELGAGSGHFAYQVLHHLLPLLSQPTLKKISVCYVLTDFVTAN
I-----------EFWKQHPSLQPFFKE---------GTLDIAYFDIEYPTDLTLQISGDS
LTPDTLNNPIILIANQVLSKLPQDAFCTESGKLSESRVRLFAPAGHQLRDWRALGQIALQ
FSDVGLDKSDYYEDAIANNILYTYSETNHPTHFLFPTVALSCLDYFRHLSKDRLMIISSD
FGYCHQNAWQG-YGEPVFKLQG---------------------SVSLPVNYHVLAAYTVQ
QGGLVLQPHRHTPDFYTQALLFGKHPTQYQETQLCYQFYSTVTETDSWQGSVQITTERME
TLSLSQL-------IGYLHSHHWDSQIFLDCFSSLLDQLD--------------------
--TATPAIRLDLIEGIHQIWTNYYP-----------------------------------
-----IGENQDLAFYLGMVLYQLAEYADAIDYFEKSIQL-------TGTDPATLYNISMC
HFHLQQLEETTTYLQKAL----QADPS------------F---EEALIFQRKLTQQQSH-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------LDSGQTH----------------------------
------------------------------------------------------------
------H
>Gloeobacter_violaceus_PCC_7421_gnl|BL_ORD_ID|714  637458091 gvip074 photosystem I assembly protein Ycf3 [Gloeobacter violaceus PCC 7421]

MPR---------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------NQRN
DNFIDKSFTVMA------------------------------------------------
------------------------------------------------------------
----------------DMILQMMP-VKRQAKEAFAYYRDGMAAQ----------------
------------------------------------------------------------
------------------------------------------------------------
--------------ADGDYAEA--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------LEYYNEALKLE---------------EDAYDRSFIHYNIGLIHA
ANGAHDVALDYYDKALEENPRLPQALNNIAVIHHFRGAKVEEEGQPEQAEEHYAKAAAAW
IRAVRLAPDNYIEAQNWLK-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------TTGRFELLY
>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|251 641249383 AM1_0257 TPR domain protein, putative [Acaryochloris marina MBIC11017]
MANVTLLDLNKRSIELLNPKFELNKRNHKANYLRMSFQVSPDKYKQIKSTELFNLYDEIL
VDTDLQFLDYSIDVYLELFLRPDLVEEFSGLLSLSDPGSSGLRCLEQLSPEHALLKTDSW
LLTSIRQTQANREVYSKTIWAYL--------CVHEEQDPLEQDLWSILSPFLQRVTESSL
TNMLGQQNSFITTQAYQ---------RWKSSVQNMDEVKQENVQVL--------------
---LKKLCEELGTISPEYHQQEFSQSSVDQLSNGLDLPKGLNSG-------SSFSTSHPS
NLGHLPIEEKRLSQSTIWDLQRQYYLQQGNTIFLQECEQQSSRQARSKASHYAQLIFSCL
RDYCAINRRHKANYQAIDASQKIYLIELGAGSGHFAYQVLHHLLPLLSQPTLKKISVCYV
LTDFVTANIEFWKQHPSLQPFFKEGTLDIAYFDIEYPTDLTLQISGDSLTPDTLNNPIIL
IANQVLSKLPQDAFCTESGKLSESRVRLFAPAGHQLRDWRALGQIALQFSDVGLDKSDYY
EDAIANNILYTYSETNHPTHFLFPTVALSCLDYFRHLSKDRLMIISSDFGYCHQNAWQGY
GEPVFKLQGSVSLPVNYHVLAAYTVQQGGLVLQPHRHTPDFYTQALLFGKHPTQYQETQL
CYQFYSTVTETDSWQGSVQITTERMETLSLSQLIGYLHSHHWDSQIFLDCFSSLLDQLDT
ATPAIRLDLIEGIHQIWTNYYPIGENQDLAFYLGMVLYQLAEYADAIDYFEKSIQLTGTD
PATLYNISMCHFHLQQLEETTTYLQKALQADPSFEEALIFQRKLTQQQSHLDSGQTHH
>Microcoleus_chthonoplastes_PCC_7420_gnl|BL_ORD_ID|8246  647572650 MC7420_165 tetratricopeptide repeat domain protein [Microcoleus chthonoplastes PCC 7420]

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------NHWLPTPRRTVNA----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------LAGAAIMVVSFWVTPSLAGDPFRPSNPRNIGDK
TEAAFESIFKQGDYKTAKDYLQQ------------AEASEGTDPLIYAMLAAIAYTEREL
EALNTYATKTRTTAEQLITSDPL-------------------RGNLYTAVGHFLEGTYNF
EKEGPVR-------------------ALSKLQKVFQYIDAAK-DIDGTDPELNLLTGHMD
LMLAVNVPFADPADAINKLETHGYPKYLAYRG---IAVAYRD------------------
-----LKKYNQAMDYV-----ERALAMTP------DNPEVLYLKAQILVHQDQPEAALDY
FEKALEKRKQLPN-----------------------------------------------
---------------------------------YSTGQIVYEQCKAQEEVDNIDRDCRA-
---------------QRNRAREG----NY-------------------------------
------------------------------------------------------------
-------------------------
>Microcystis_aeruginosa_NIES_843_gnl|BL_ORD_ID|3342  641537342 MAE_33430 probable glycosyl transferase [Microcystis aeruginosa NIES-843]

MP-------------------------------------KLSLCMIVKNEAENLRRCLDS
VK----------------------------------------------------------
------------------------------------------------------------
------------------------------GVVDEMI-----------------------
------------------------------------------------------------
-VMDTGSTDDT-----------------------IAIAQSYGA-----IVPSYDWRGNFS
DARNEALKYVTGDWILVLDADEELNAAIVPKMRRAMEKE---------------------
ENLVINL------------------IRHEIGAVQSPYSLISRLFRRHPQVTFTRPYHSII
DDNVAILLKKEPGWKIVEL-PE-----------------------IAIFHYGYTVDKIAS
LDKFERARK---------------------------------------------------
-----------------------------------------AMEGFYQQHPHDPY-----
-------VCSKLGGLYLKIGRDK------EGFKLLKHGLKCHGSNPHILYELYYHLANYY
YS-VEEFKQS------------ADHFVKAIKQPILDKLKLGAYNNFGGLLYEAENYEAAL
------------------------------SVFEKTVEID----------------PSYA
DGY---------------------------------------------------------
-------------YNLGLVLKQLHRLPESIKAYKKALKLNQDNPTIYQNLGVAYIVF---
------------------------------------------------------------
-----GSYNEAIKIWQKGLQL--------------LKDQGNVSRAEMLQETLEALGASVL
RDE---------------------Q
>Nostoc_sp_PCC_7120_gnl|BL_ORD_ID|5232  637235331 all4926 hypothetical protein [Nostoc sp. PCC 7120]

MLTRLFQWLKTFDKH---------------------------------------------
--------------------------------PVDDPQTDYFQGVKEQVAEEPPELTNGD
LELLFNQLLQGVNQGRGQQWAIRYLQRMEDRISVERWIDWLLVFGEKLLMSPAPNHHLGK
QMVTLGELGIGKVGELSYDIGIRLLDREFIEINDVNEETKA------------PSTTVPE
TSDNLPDSPGQELIRHLGDLLWESREAETATTQAKLEIVDEDTITSLQELSWEYHAVPTA
SVDEDTIENLQELNWEYHIAP---TELVDDNIIENPPELSWQEQTA--PTDVVD------
ATTNLQELSWEYQQAEFTAPPLLMPAQED---------------------VISNLSELVL
DYRE----------QNSAAIVSTQSNWDESLVNLDPNVAYTLDELMVRLDQSANLVQQLA
ANLTVQ--------------TNQQPPAIIN-EHSNAFVKAQELFYQGLQQAKQGDLLGAI
ANYEQAIQLNPSSYEYWFNRGLTLFHLERFV--EAIA-----------------------
---------SYDQAIEIKPDY----YKAWYNRGGTLGQLGLYEEAVASLKQAISIQ----
PDMPGAWSSKGWAEL----------KLGQIGEAIASYDEALLLSPE-DQENWYYRGIALG
VDEQYEAAIDSYDKALEIQPDFHEVWIDRGVVLFNLGQWSEAIASWDQALSIQADFYLAW
YNRGVALENLGRRAEAIASYKQAIEIKPDFHLAWYNQAVALFYLERFL--------EAIV
CYDNALQIKL---------------DYWEAWIGRG------------------TAIGNLN
ETDT--PLNLLTTIAADNSTL--------KQAGYEGKLASYQEGLKHIRPDTHPEGWGRL
HLAIANSYYEQGKKYSTSR---------NYWRKAVTEYNQALLTLTSAGFPQLHLEVLQS
LVKALLGLGQTTQAQEFQQRGSRLLQQFLSEPTRTAEIKKQLALKFAGFGQLAVDVAVEY
GDLVEAWEIAEQGKNACLTWLLCGWNADIQALNYRAVQQLLNPHTAIIYWHISPVALHTF
IIKDQAPSPILVFTPVQDLGAINATPLQDLPLPEATRRLIAFENWLEDWQQNYQDYHQQA
QDQQSKSNHPWRLEMEHKLLQLKEILEIDTIQQELEDITQLILVPHRDLFRVPLHCLFQI
SNSPETIPIADIAYLPNIQIALSGKQANIGQFVNQTLLSVEYPDNTAYPTLRFANLEAEV
VSQMFNNRQRLQGGEATKNNFEDAFFSNYSVLHFAGQAINRLTDPQRSELALAGEDKFTL
AEICETNLSTYNLVTLSTCETVTNTNQVTTSEYVDLVSAFFYKGVSQVVSTLWTVESSAS
ALVIIEFYRRLQLVESASTALAEATGWLRELTASELTQWYEDLLNNLDPQELKLRAYLAT
HLYRISKMPADKNLYSHPYYWAAFTITGNPNK
>Synechococcus_elongatus_PCC_6301_gnl|BL_ORD_ID|1305  637616969 syc1304_c hypothetical protein [Synechococcus elongatus PCC 6301]

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-QITAAAQHDYQQAIAAYQAGEFEAAIAQLDRLLGDVPDWAAALGLQGLCYYCCDQRETG
ITLLRRAIALDPTDPTHFNNLGNLLQRQGHLTEALERLTQALAIDPTHVAARFNRAITLQ
KLGDPATALQDYQQLLE---------ADPDNPEIRYNSAHAALAIGDWDFGLPAYEARCQ
QLQHFPEIEASLKLPRWQGQDLDQQTLLVWGEQGFGDRLMGA--RWIPLLRQRYPQARIV
--------------WQTSPSLVRLFQTLADD----------RLMVLAEGAELPVCDWQVP
LLSLMLIFQSDRNRLPWHGPYFFPHK------GDFLPASDRPRLGLVWSA-GRNPA---Q
SAEF---------AANKSCPLALLWSVLSVSGWDVVSLQVDEARQDLQTLSDPLLDLGSE
IGDFQDTVDRLAHLDLLITVDTAIAHLGGMIGLPTWVL----------------------
----------------LPAVPDWRWELSGATTPWYPSLRLFRQPSPGDWSGAIAELQT-A
LAEFQPAPQHWDYRGELSIADWIQAADRAFTAQNWPRAEWLIRQAVAI------------
AP---------------------EEPSFHRALGRSLKQQGDYAGAAQALAIACELAPTQA
EFWHERSSLEYYDNQLTAALNSLNQAIALQGATADHLISRGVLHYRLGQFPESCADYDAA
A------AIAPESPLLRCNRGFLQ------LHWGNWLQGWPDLEVRFDFQSDLDPFQYRQ
LAPAWQGEPLGQQTLLIWGEQGLGDHLLFCRWLPELRLQHPQAQLIFVTDPLLERLMQQL
ADDRLQICCLDEPVPACDRQVALMSLPAIAQTTPATVPWRGAYFQSSMPPLRCAETLQVG
FVWASGKRSSPETARLYREKSCPLNELLPALLAVPAVDYYSFQVGADVAELQPWLEQSDR
LFDLSEQLQDFQDTADWLAEMDVLISVDTAVANLAGMMALPVWTLLPEPANWRWGLTGHT
TPWYPSMRLYRQTQRGNWSGAIAQIQQDLQQLSRDRDCLVT
>Thermosynechococcus_elongatus_BP_1_gnl|BL_ORD_ID|2426  637315072 tll2427 putative glycosyl transferase [Thermosynechococcus elongatus BP-1]

MAPL--------------------------------------------------------
---------------------------LSLCMIVKNEAHQLRRCLQSVQPW---------
------------------------------------------------------------
--------------VDEIIIVDTGSTDGTIAIACE-------------------------
------------------------------------------------------------
------------------------------------------------------------
---------FTPHVHAVAWQGDFAAARNAALAQATGEWVFYIDADEELVVTDAHWQDQLT
APGA------HAINQWSLLRREQSSDRNWSEFWNVRFGR--------------RFPDLHF
AGALHEQLCY--------------------------------------------------
-----------RER------EAVVGELQGVYLIHH-------------------------
---------------NQQSQEQFLAKIRDRNIPILETMVQQGDRRLQNLV---CLGDHYA
ACGDS-DRSQAWYEQALEEIASAVEQGILPRETTWLRHLLFWVSYRAFEAKDYETAQYYL
SYGLRFFDRYPPLLYVA------GLFVFELGLPRGALPYFHRCLDLFEAGSYDRTEPFDR
QWMTTQPA--YSLGYTYMTLQERDRAIAYFQKTLKFNP----------------------
--DYPPAQMY--LEQLL---------------------------RASAN-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------QG
>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|251 641249383 AM1_0257 TPR domain protein, putative [Acaryochloris marina MBIC11017]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------ANVTLLDLNKRSIE
LLNPKFELNKRNHKANYLRMSFQVSPDKYKQ-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----IKSTELFNLYDEILVDTDLQFLDYSIDVYLEL------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------FLRPDLVEEFSGLLSLSDPGSSGLRCLEQLSPEHALLKTDSWLLTSIRQTQ
ANREVYSKTIWAYLCVHEEQDPLEQDLWSILSPFLQRVTESSLTNM--------------
-------------------LGQQNSF-ITTQAYQRWKSSVQNMDEVKQ------------
--------ENVQVLLKKLCEELG------TISPEYHQQEFSQSSVDQLSNGL-DLPKGLN
SGSSFSTSHPSNLGHLPIEEKRLSQSTIWDLQRQYYLQQGNTIFLQECEQQSSRQARSKA
S--HYAQLIFSCLRDYCAINRRHKANYQAIDASQKIYLIELGAGSGHFAYQVLHHLLPLL
SQP--------TLKKISVCYVLTDFVTANIEFWKQHPSLQPFFKEGTLDIAYFD------
IEYPTDLTLQIS-----------------------------GDSLTPDTLNNPIILIANQ
VLSKLPQDAFCTESGKLSESRVRLFAPAGHQLR------------------DWRALGQIA
LQFSD-------------------------------------------------------
-----------------------------------------------VGLDKSD------
-------------------------------------------YY---------------
---------------------------------------EDAIANNILYT----------
--------------------------YSETNHPTHFLFPTVALSCLDYFRHLSKDRLMII
SSDFGYCHQNAWQGYGEPVFK---------LQGSVSLPVNYHVLAAYTVQQGGLVLQPHR
HTPDFYTQALLFGKHPTQYQETQLCYQFYSTVTETDSWQGSVQITTERMETLSLSQLIGY
LHSHHWDSQIFLDCFSSLLDQLDTATPAIRLDLIEGIHQIWTNYYPIGENQDLAFYLGMV
LYQLAEYADAIDYF-------EKSIQLTGTDPATLYNISMCHFHLQQLEETTTYLQKALQ
ADPSFEEA-------LIFQRKLTQQ------------QSHLDSGQTHH------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------
