>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|251 641249383 AM1_0257 TPR domain protein, putative [Acaryochloris marina MBIC11017]
MANVTLLDLNKRSIELLNPKFELNKRNHKANYLRMSFQVSPDKYKQIKSTELFNLYDEIL
VDTDLQFLDYSIDVYLELFLRPDLVEEFSGLLSLSDPGSSGLRCLEQLSPEHALLKTDSW
LLTSIRQTQANREVYSKTIWAYLCVHEEQDPLEQDLWSILSPFLQRVTESSLTNMLGQQN
SFITTQAYQRWKSSVQNMDEVKQENVQVLLKKLCEELGTISPEYHQQEFSQSSVDQLSNG
-LDLPKGLNSGSSFSTSHPSNLGHLPIEEKRLSQSTIWDLQRQYYLQQGNTIFLQECEQQ
SSRQARSKASHYAQLIFSCLRDYCAINRRHKANYQAIDASQKIYLIELGAGSGHFAYQVL
HHLLPLLSQPTLKKISVCYVLTDFVTANIEFWKQHPSLQPFFKEGTLDIAYFDIEYPTDL
TLQISGDSLTPDTLNNPIILIANQVLSKLPQDAFCTESGKLSESRVRLFAPAGHQLRDWR
ALGQIALQFSDVGLDKSDYYEDAIANNILYTYSETNHPTH--------------------
---FLFPTVALSCLDYFRHLSKDRLMIISSDFGYCHQNAWQGYGEPVFKLQGSVSLPVNY
------------HVLAAYTVQQGGLVLQPHRHTPDFYTQALLFGKHPTQY----------
-----------------QETQLCYQFYSTVTET---------DSWQGSVQITTERMETLS
LSQLIGYLHSHHWDSQI-------------------------------FLDCFSSLLDQL
DTATPAIRLDLIEG--IHQIWTNYYPIG-------------------------ENQDLAF
YLGMVLYQLAEYADAIDYFEKSIQL---------TGTDPATL-----YNISMCHFHLQQL
EETTTYLQKALQADPS---FEEALI-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------FQRKL---------------------
-------------------------------------------------------TQQQ-
---SHLDSGQTHH-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Gloeobacter_violaceus_PCC_7421_gnl|BL_ORD_ID|714 637458091 gvip074 photosystem I assembly protein Ycf3 [Gloeobacter violaceus PCC 7421]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------PRNQRNDNF----------
------------------------------------------------------------
------------------------------------------------IDKSFTVMADMI
LQMMPVKRQAK-------------------------------------------EAFAYY
RDGMAAQADGDYAEALEYYNEALKLEE-------DAYDRSFI----HYNIGLIHAANGAH
DVALDYYDKALEENPR---LPQALNNIAVIHHFRGAKVEEEGQPEQAEEHYAKAAAAWIR
AVRLAPDNYIE-------------------------------------------------
------------------------------------------------------------
----------------------------------AQNWLKTTGRFELLY-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Microcoleus_chthonoplastes_PCC_7420_gnl|BL_ORD_ID|8246 647572650 MC7420_165 tetratricopeptide repeat domain protein [Microcoleus chthonoplastes PCC 7420]
M-----------------------------------------------------------
----------------------------------NHWLPTPRRTVNALAGAAIMVVSF--
------------------------------------------------------------
------------------------------------------------------------
---WVTPSLAGDPFRPSNPRNIGD------------------------------------
------------------------------------------------------------
--------------------------------KTEAAFESIFKQGDYKTAKDYL------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------QQAEASEGTDPLIYAMLA------AI
AYTERELEALNTYATKTRTTAEQLITSDPLR--GNLYTAVGHFLEGTYNF----------
--------EKEGPVRALSKLQKVFQYIDAAKDI-----DGTDPELNLLTGHMDLMLAVN-
--------------------------------------------------VPFADPADAI
NK-----------------LETHGYPKY----------------------------LAYR
GIAVAYRDLKKYNQAMDYVERALAM---------TPDNPEVL-----YLKAQILVHQDQP
EAALDYFEKALEKRKQLPNYSTGQI-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------VYEQCKA-------------------
--------------------------------------------------------QEEV
DNIDRDCRAQRNRAREGNY-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Microcystis_aeruginosa_NIES_843_gnl|BL_ORD_ID|3342 641537342 MAE_33430 probable glycosyl transferase [Microcystis aeruginosa NIES-843]
M-----------------------------------------------------------
-------------------------PKLSLCMIVKNEAENLRRCLDSVKG----------
------------------------------------------------------------
------------------------------------------------------------
---VVDEMIVMDTGSTDDTIAIAQ------------------------------------
------------------------------------------------------------
--------------------------------SYGAIVPSYDWRGNFSDARNEA------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------LKYVTGDWILVLDADEELNAAI
VPKMRRAMEKEENLV--INLIRHEIGAV--QSPYSLIS-RLFRRHPQVTFTRPYHSIIDD
NVAILLKKEPGWKIVELPEIAIFHYGYTVDKIASLDKFERARKAMEGFYQQHPHDPYVC-
--SKLGGLYLKIGRDKEGFKLLKHGLKCHGSNPHILYELYYHLANYYYSVEEFKQSADHF
VKAIKQPILDK--------LKLGAYNNFGGLLYEAENYEAALSVFEKTVEIDPSYADGYY
NLGLVLKQLHRLPESIKAYKKALKL---------NQDNPTIY-----QNLGVAYIVFGSY
NEAIKIWQKGLQLLKDQGNVSRAEM-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------LQETLEALGASVLRDEQ---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Thermosynechococcus_elongatus_BP_1_gnl|BL_ORD_ID|2426 637315072 tll2427 putative glycosyl transferase [Thermosynechococcus elongatus BP-1]
M-----------------------------------------------------------
------------------------APLLSLCMIVKNEAHQLRRCLQSVQP----------
------------------------------------------------------------
------------------------------------------------------------
---WVDEIIIVDTGSTDGTIAIAC------------------------------------
------------------------------------------------------------
--------------------------------EFTPHVHAVAWQGDFAAARNAA------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------LAQATGEWVFYIDADEELVVTD
AHWQDQLTAPGAHAINQWSLLRREQSSD--RNWSEFWNVRFGRRFPDLHFAGALHE----
---QLCYREREAVVGELQGVYLIHHNQQSQEQFLAKIRDRNIPILETMVQQGDRRLQNL-
--VCLGDHYAACGDSDR-------------------------------SQAWYEQALEEI
ASAVEQGILPRETTWLRHLLFWVSYRAF-----EAKDYETAQYYLSYGLRFFDRYPPLLY
VAGLFVFELGLPRGALPYFHRCLDLFEAGSYDRTEPFDRQWMTTQPAYSLGYTYMTLQER
DRAIAYFQKTLKFNPD---YPPAQM-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------YLEQLLRASANQG-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Nostoc_sp_PCC_7120_gnl|BL_ORD_ID|5232 637235331 all4926 hypothetical protein [Nostoc sp. PCC 7120]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------LTRLF----QW-----LKTFDKHPVDDPQTD
YFQGVKEQVAEEPPELTN----GDLELLFNQLLQGVNQGRGQQWAI---RYLQRMEDRIS
VERWIDWLLVFGE-KLLMSPAPNHHLGKQMVTLGELGIGKVGELSYDIGIRLLDREFIEI
NDVNEETKAPSTTVPETSDNLPDSPGQELI--RH---------LGDLLWESREA------
--------ETATTQAKL-EIVDEDTITSLQE----------LSWEYHAVPTASVDEDTIE
NLQELNWEYHIAPTELVDDNIIENPPELS--WQEQTAPTDVVDATTNLQ---ELSWEYQQ
AE-FTAPPLLMPAQEDVISNLSELVLDYREQNSAAIVSTQSNWDESLVNLDP------NV
AYTLDELMVRLDQSANLVQQLAANLTVQTNQQPPAI------INEHSNAF----------
--------------------------VKAQELFYQGLQQAKQGDLLGAIANYEQAIQLN-
--PSSYEYWFNRGLTLF-------------------------------HLERFVEAIASY
DQAIEIKPDYY-----------KAWYNRGGTLGQLGLYEEAVASLKQAISIQPDMPGAWS
SKGWAELKLGQIGEAIASYDEALLL---------SPEDQENW-----YYRGIALGVDEQY
EAAIDSYDKALEIQPD---FHEVWIDRGVVLFNLG--------------QWSEAIASWDQ
ALSIQADFYLAWYNRGVALENLGRRAEAIASYKQAIEIKPDFHLAWYNQAVALFYLERFL
EAIVCY-------DNAL------QIKLDYWEAWIGRGT----------------AIGNLN
E----TDTPLNLLTTIAADNSTLKQAGYEGKLASYQEGLKHIR-PDTHPEGWGRLHLAIA
NSYYEQGKKYS--TSRNYWRKA--VTEYNQALLTLTSAGFPQLHL-----EVLQSLVKAL
LGLGQTTQAQEFQQRGSRL--LQQFLSEPTRTAEIKKQLALKFAGFGQLAVDVAVEYGDL
VEAWEIAEQGKNACLTWLLCGWNADIQALNYRAVQQLLNPHTAIIYWHISPVALHTFIIK
DQAPSPILVFTPVQDLGAINATPLQDLPLPEATRRLIAFENWLEDWQQNYQDYHQQAQDQ
QSKSNH--PWRLEMEHKLLQLKEILEIDTIQQELEDITQLILVPHRDLFRVPLHCLFQIS
NSPETIPIADIAYLPNIQIALSGKQANIGQFVNQTLLSVEYPDNTAYPTLRFANLEAEVV
SQMFNNRQRLQGGEATKNNFEDAFFSNYSVLHFAGQAINRLTDPQRSELALAGEDKFTLA
EICETNLSTYNLVTLSTCETVTNTNQVTTSEYVDLVSAFFYKGVSQVVSTLWTVESSASA
LVIIEFYRRLQLVESASTALAEATGWLRELTASELTQWYEDLLNNLDPQEL-KLRAYLAT
HLYRISKMPADKNLYSHPYYWAAFTITGNPNK
>Synechococcus_elongatus_PCC_6301_gnl|BL_ORD_ID|1305 637616969 syc1304_c hypothetical protein [Synechococcus elongatus PCC 6301]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-QITAAAQHDYQQAIAAYQAGEFEAAIAQLDRLLGDVPDWAAALGLQGLCYYCCDQRETG
-ITLLRRAIALDPTDPTHFNNLGNLLQRQGHLTEALER-LTQALAIDPTHVAARFNRAIT
LQKLGDPATALQDYQQLLEADPDNPEIRYNSAHAALAIG-----DWDFGLPAYEARCQQL
QHFPE---------IEASLKLPRWQGQDLD--QQTLLVWGEQGFGDRLMGARWIPLLRQR
YPQARIVWQTSPSLVRLFQTLADDRLMVLAEGA----ELPVCDWQ---VPLLSLMLIFQS
DRNRLPWHGPYFFPHKGDFLPASDRPRLGLVWSAGRNPAQSAEFAANKSCPLALLWSVLS
VSGWDVVSLQVDEARQDLQTLSDPLLDL----GSEIGDFQDTVDR-LAHLD---------
------LLITVDTA---IAHLGGMIGLPTWVLLPAVPDWRWELSGATTPW----------
--------------------------YPSLRLF----RQPSPGDWSGAIAELQTALAEF-
--QPAPQHWDYRGEL------------------------------------SIADWIQAA
DRAFTAQNWPR-----------AEWL------------------IRQAVAIAPEEPSFHR
ALGRSLKQQGDYAGAAQALAIACEL---------APTQAEFW-----HERSSLEYYDNQL
TAALNSLNQAIALQGA---TADHLISRGVLHYRLG--------------QFPESCADYDA
AAAIAPESPLLRCNRGFLQLHWGNWLQGWPDLEVRFDFQSDLDPFQYRQLAPAWQGEPLG
QQTLLIWGEQGLGDHLLFCRWLPELRLQHPQAQLIFVTDPLLERLMQQLADDRLQICCLD
EPVPACDRQVALMSLPAIAQTTPATVPWRG--AYFQSSMPPLRCAETLQVGF--------
--VWASGKRSSPETARLYREKSCPLNELLPALLAVPAVDYYSFQVGADVAELQPWLEQSD
RLFDLSEQLQDFQDTADWLAEMDVLISVDTAVANLAGMMAL-------------------
------------------------------------------------------------
-----------PVWTL----------LPEP---------ANW--RW--------------
-GLTGHTTPW--------------------------------------------------
----------------------------------------------YPSMR---------
------------------------------------------------------------
------------------------------------------------------------
-----LYRQTQ-----------RGNW-----SGAIAQIQQDL------QQLSRDRDCLVT
--------------------------------
