>Acaryochloris_marina_MBIC11017_gnl|BL_ORD_ID|251 641249383 AM1_0257 TPR domain protein, putative [Acaryochloris marina MBIC11017]
MANVTLLDLNKRSIELLNPKFELNKRNHKANYLRMSFQVSPDKYKQIKSTELFNLYDEIL
VDTDLQFLDYSIDVYLELFLRPDLVEEFSGLLSLSDPGSSGLRCLEQLSPEHALLKTDSW
LLTSIRQTQANREVYSKTIWAYLCVHEEQDPLEQDLWSILSPFLQRVTESSLTNMLGQQN
SFITTQAYQRWKSSVQNMDEVKQENVQVLLKKLCEELGTISPEYHQQEFSQSSVDQLSNG
-LDLPKGLNSGSSFSTSHPSNLGHLPIEEKRLSQSTIWDLQRQYYLQQGNTIFLQECEQQ
SSRQARSKASHYAQLIFSCLRDYCAINRRHKANYQAIDASQKIYLIELGAGSGHFAYQVL
HHLLPLLSQPTLKKISVCYVLTDFVTANIEFWKQHPSLQPFFKEGTLDIAYFDIEYPTDL
TLQISGDSLTPDTLNNPIILIANQVLSKLPQDAFCTESGKLSESRVRLFAPAGHQLRDWR
ALGQIALQFSDVGLDKSDYYEDAIANNILYTYSETNHPTH--------------------
---FLFPTVALSCLDYFRHLSKDRLMIISSDFGYCHQNAWQGYGEPVFKLQGSVSLPVNY
------------HVLAAYTVQQGGLVLQPHRHTPDFYTQALLFGKHPTQY----------
-----------------QETQLC----YQFYSTVT---------ETDSWQGSVQITTERM
ETL----------------------------SLSQLIGYLHSHHWDSQIFLD-CFSSLLD
QLDTATPAIRLDLIEG--IHQIWTNYYPIG-------------------------ENQDL
AFYLGMVLYQLAEYADAIDYFEKSIQL---------TGTDPATL-----Y-NISMCHFHL
QQLEETTTYLQKALQADPS---FEEALI--------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------FQRKL--------------------------------
--------------------------------------------TQQQ----SHLDSGQT
HH----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>Gloeobacter_violaceus_PCC_7421_gnl|BL_ORD_ID|714 637458091 gvip074 photosystem I assembly protein Ycf3 [Gloeobacter violaceus PCC 7421]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------PRNQRNDN-------------------------
-------------------------------------------------FIDKSFTVMAD
MILQMMPVKRQAK-------------------------------------------EAFA
YYRDGMAAQADGDYAEALEYYNEALKLEE-------DAYDRSFI-----HYNIGLIHAAN
GAHDVALDYYDKALEENPR---LPQALNNIAVIHH-------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------FRGAK--------------------------------
--------------------------------------------VEEE----GQPEQAEE
HYAKAAAA----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------WIR
AVRLAPDNYIEAQNWLKTTGRFELLY----------------------------------
---------------------
>Microcoleus_chthonoplastes_PCC_7420_gnl|BL_ORD_ID|8246 647572650 MC7420_165 tetratricopeptide repeat domain protein [Microcoleus chthonoplastes PCC 7420]
M-----------------------------------------NHWLPTPRRTVNALAGAA
IMVVSFWVTPSL------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------AGDPFRPSNPRNIGD------------------------------------
------------------------------------------------------------
--------------------------------KTEAAFESIFKQGDYKTAKDYLQ-----
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------QAEASEGTDPLIYAMLA------AI
AYTERELEALNTYATKTRTTAEQLITSDPLR--GNLYTAVGHFLEGTYNF----------
--------EKEGPVRALSKLQKV----FQYIDAAK---------DIDGTDPELNLLTGHM
DLML---------------------------------------------AVNVPFADPAD
AINK-----------------LETHGYPKY----------------------------LA
YRGIAVAYRDLKKYNQAMDYVERALAM---------TPDNPEVL-----Y-LKAQILVHQ
DQPEAALDYFEKALEKRKQLPNYSTGQI--------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------VYEQCK-------------------------------
--------------------------------------------AQEEVDNIDRDCRAQR
NRAREGNY----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>Microcystis_aeruginosa_NIES_843_gnl|BL_ORD_ID|3342 641537342 MAE_33430 probable glycosyl transferase [Microcystis aeruginosa NIES-843]
M-----------------PK------------LSLCMIVKNEAENLRRCLDSVKGVVDEM
IVMDTGSTDDTIAIAQ--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------SYGAIVPSYDWRGNFSDAR---------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------NEALKYVTGDWILVLDADEELNAAI
VPKMRRAMEKEENLV--INLIRHEIGAV--QSPYSLIS-RLFRRHPQVTFTRPYHSIIDD
NVAILLKKEPGWKIVELPEIAIF----HYGYTVDKIASLDKFERARKAMEGFYQQHPHDP
YVCSKLGGLYLKIGRDKEGFKLLKHGLKCHGSNPHILYELYYHLANYYYSVE-EFKQSAD
HFVKAIKQPILDK--------LKLGAYNNFGGLLYEAENYEAALSVFEKTVEIDPSYADG
YYNLGLVLKQLHRLPESIKAYKKALKL---------NQDNPTIY-----Q-NLGVAYIVF
GSYNEAIKIWQKGLQLLKDQGNVSRAEM--------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------LQETL--------------------------------
--------------------------------------------EALG----ASVLRDEQ
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>Thermosynechococcus_elongatus_BP_1_gnl|BL_ORD_ID|2426 637315072 tll2427 putative glycosyl transferase [Thermosynechococcus elongatus BP-1]
M----------------------------APLLSLCMIVKNEAHQLRRCLQSVQPWVDEI
IIVDTGSTDGTIAIAC--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------EFTPHVHAVAWQGDFAAAR---------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------NAALAQATGEWVFYIDADEELVVTD
AHWQDQLTAPGAHAINQWSLLRREQSSD--RNWSEFWNVRFGRRFPDLHFAGALHE----
---QLCYREREAVVGELQGVYLI----HHNQQSQEQFLAKIRDRNIPILETMVQQGDRRL
QNLVCLGDHYAACGDSDRSQA--------------------------------WYEQALE
EIASAVEQGILPRETTWLRHLLFWVSYRAF-----EAKDYETAQYYLSYGLRFFDRYPPL
LYVAGLFVFELGLPRGALPYFHRCLDLFEAGSYDRTEPFDRQWMTTQPAY-SLGYTYMTL
QERDRAIAYFQKTLKFNPD---YPPAQM--------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------YLEQL--------------------------------
--------------------------------------------LRAS------ANQG--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>Nostoc_sp_PCC_7120_gnl|BL_ORD_ID|5232 637235331 all4926 hypothetical protein [Nostoc sp. PCC 7120]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------LTRLF----QW-----LKTFDKHPVDDPQTD
YFQGVKEQVAEEPPELTN----GDLELLFNQLLQGVNQGRGQQWAI---RYLQRMEDRIS
VERWIDWLLVFGE-KLLMSPAPNHHLGKQMVTLGELGIGKVGELSYDIGIRLLDREFIEI
NDVNEETKAPSTTVPETSDNLPDSPGQELI--RH---------LGDLLWESREA------
--------ETATTQAKL-EIVDEDTITSLQE----------LSWEYHAVPTASVDEDTIE
NLQELNWEYHIAPTELVDDNIIENPPELS--WQEQTAPTDVVDATTNLQ---ELSWEYQQ
AE-FTAPPLLMPAQEDVISNLSELVLDYREQNSAAIVSTQSNWDESLVNLDP------NV
AYTLDELMVRLDQSANLVQQLAANLTVQTNQQPPAI------INEHSNAF----------
----------------VKAQELFYQGLQQAKQGDLLGAIANYEQAIQLNPSSYEYWFNRG
LTL----------------------------------------------FHLERFVEAIA
SYDQAIEIKPDYY-----------KAWYNRGGTLGQLGLYEEAVASLKQAISIQPDMPGA
WSSKGWAELKLGQIGEAIASYDEALLL---------SPEDQENW-----Y-YRGIALGVD
EQYEAAIDSYDKALEIQPD---FHEVWIDRGVVLFNLGQWSEAIASWDQALSIQADFYLA
WYNRGVALENLGRRAEAIASYKQAIEIKPDFHLAWYNQAVALFYLERFLEAIVCY-----
--DNAL------QIKLDYWEAWIGRGT----------------AIGNLNE----TDTPLN
LLTTIAADNSTLKQAGYEGKLASYQEGLKHIR-PDTHPEGWGRLHLAIANSYYEQGKKYS
--TSRNYWRKA--VTEYNQALLTLTSAGFPQLHL-----EVLQSLVKALLGLGQTTQAQE
FQQRGSRL--LQQFLSEPTRTAEIKKQLALKFAGFGQLAVDVAVEYGDLVEAWEIAEQGK
NACLTWLLCGWNADIQALNYRAVQQLLNPHTAIIYWHISPVALHTFIIKDQAPSPILVFT
PVQDLGAINATPLQDLPLPEATRRLIAFENWLEDWQQNYQDYHQQAQDQQSKSNH--PWR
LEMEHKLLQLKEILEIDTIQQELEDITQLILVPHRDLFRVPLHCLFQISNSPETIPIADI
AYLPNIQIALSGKQANIGQFVNQTLLSVEYPDNTAYPTLRFANLEAEVVSQMFNNRQRLQ
GGEATKNNFEDAFFSNYSVLHFAGQAINRLTDPQRSELALAGEDKFTLAEICETNLSTYN
LVTLSTCETVTNTNQVTTSEYVDLVSAFFYKGVSQVVSTLWTVESSASALVIIEFYRRLQ
LVESASTALAEATGWLRELTASELTQWYEDLLNNLDPQEL-KLRAYLATHLYRISKMPAD
KNLYSHPYYWAAFTITGNPNK
>Synechococcus_elongatus_PCC_6301_gnl|BL_ORD_ID|1305 637616969 syc1304_c hypothetical protein [Synechococcus elongatus PCC 6301]
M-----------------------------------------------------------
----------------Q-------------------------------------------
------------------------------------------------------------
--ITAAAQHDYQQAIAAYQAGEFEAAIAQLDRLLGDVPDWAAALGLQGLCYYCCDQRETG
-ITLLRRAIALDPTDPTHFNNLGNLLQRQGHLTEALER-LTQALAIDPTHVAARFNRAIT
LQKLGDPATALQDYQQLLEADPDNPEIRYNSAHAALAIG-----DWDFGLPAYEARCQQL
QHFPE---------IEASLKLPRWQGQDLD--QQTLLVWGEQGFGDRLMGARWIPLLRQR
YPQARIVWQTSPSLVRLFQTLADDRLMVLAEGA----ELPVCDWQ---VPLLSLMLIFQS
DRNRLPWHGPYFFPHKGDFLPASDRPRLGLVWSAGRNPAQSAEFAANKSCPLALLWSVLS
VSGWDVVSLQVDEARQDLQTLSDPLLDL----GSEIGDFQDTVDR-LAHLD---------
------LLITVDTA---IAHLGGMIGLPTWVLLPAVPDWRWELSGATTPW----------
----------------YPSLRLF----RQPSPGDWSGAIAELQTALAEFQPAPQHWDYRG
EL---------------------------------------------------SIADWIQ
AADRAFTAQNWPR-----------AEWL------------------IRQAVAIAPEEPSF
HRALGRSLKQQGDYAGAAQALAIACEL---------APTQAEFW-----H-ERSSLEYYD
NQLTAALNSLNQAIALQGA---TADHLISRGVLHYRLGQFPESCADYDAAAAIAPESPLL
RCNRGFLQLHWGNWLQGWPDLEVRFDFQSDLDPFQYRQLAPAWQGEPLGQQTLLIWGEQG
LGDHLLFCRWLPELRLQHPQAQLIFVTDPLLERLMQQLADDRLQICCLDEPVPACDRQVA
LMSLPAIAQTTPATVPWRG--AYFQSSMPPLRCAETLQVGF----------VWASGKRSS
PETARLYREKSCPLNELLPALLAVPAVDYYSFQVGADVAELQPWLEQSDRLFDLSEQLQD
FQDTADWLAEMDVLISVDTAVANLAGMMAL------------------------------
------------------------------------------------------------
PVWTL----------LPEP---------ANW--RW---------------GLTGHTTPW-
------------------------------------------------------------
-----------------------------------YPSMR--------------------
------------------------------------------------------------
------------------------------------------------------LYRQTQ
-----------RGNW-----SGAIAQIQQDL------QQLSRDRDCLVT-----------
---------------------
